### ISSUE TITLE
如何控制折线图的线的粗细和lengend文字的大小

### ISSUE THREAD

**Issue by christianxiao** [antvis/mini-program-f2-demos#7]
默认绘制的图像总感觉线太粗了，分辨率不够

**Comment by simaQ** [comment]
* 线的粗细可以在 .size() 方法中指定：https://www.yuque.com/antv/f2/api-geometry#eigtss
* legend 的文字大小设置方法请翻阅 API 文档：https://www.yuque.com/antv/f2/api-legend#ol5opw
